Repository project-primera/ongeki-score, pull requests merged in 2025-05, with the labels that each got.

#926 フィルタの改良
  OngekiScoreLog/resources/assets/js/sortTable.js
  OngekiScoreLog/resources/views/layouts/components/user/song_filter.blade.php
Labels: Type: Bug, Type: Feature, Scope: Application

#928 レーティング対象曲の統計の数値を右揃えで表示するようにした (#876)
  OngekiScoreLog/resources/assets/sass/style.scss
  OngekiScoreLog/resources/views/user_rating.blade.php
Labels: Type: Feature, Scope: Application

#927 更新差分にプラチナスコアの情報を追加
  OngekiScoreLog/app/Http/Controllers/ViewUserProgressController.php
  OngekiScoreLog/resources/assets/sass/_user_progress.scss
  OngekiScoreLog/resources/views/user_progress.blade.php
Labels: Type: Feature, Scope: Application

#938 不要なリーセント系処理を削除
  OngekiScoreLog/resources/assets/js/bookmarklets/getScore.ts
Labels: Type: Refactoring, Scope: Application, Scope: Bookmarklet

#921 feat: 履歴ベースのスコア取得
  OngekiScoreLog/app/Http/Controllers/api/v2/UserController.php
  OngekiScoreLog/resources/assets/js/bookmarklets/getScore.ts
Labels: Type: Feature, Scope: Application, Scope: Bookmarklet

#940 Release 0.21.0
  .github/dependabot.yml
  OngekiScoreLog/app/Http/Controllers/ViewUserProgressController.php
  OngekiScoreLog/app/Http/Controllers/api/v2/UserController.php
  OngekiScoreLog/resources/assets/js/bookmarklets/getScore.ts
  OngekiScoreLog/resources/assets/js/sortTable.js
  OngekiScoreLog/resources/assets/sass/_user_progress.scss
  OngekiScoreLog/resources/assets/sass/style.scss
  OngekiScoreLog/resources/views/layouts/components/user/song_filter.blade.php
  OngekiScoreLog/resources/views/user_progress.blade.php
  OngekiScoreLog/resources/views/user_rating.blade.php
Labels: Type: Release

#942 Release 0.21.1
  OngekiScoreLog/app/Services/OngekiUtility.php
Labels: Type: Release

#943 Perfect Shining!!にてPスコア枠での計算が行えない問題を修正 が修正できていない問題を修正
  OngekiScoreLog/app/Services/OngekiUtility.php
Labels: Type: Bug

#944 Release 0.21.2
  OngekiScoreLog/app/Services/OngekiUtility.php
Labels: Type: Release
